version: "2"
services:
  web:
    build: .
    image: "node:8.4.0"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm run build; node server/workers.js'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mailcatcher
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mailcatcher:
    image: rylwin/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"